# 02 Linear Algebra

## 2.1 Abelian Group

Consider $(\mathbb{R} \setminus \{-1\}, \star)$ with

$$
    a \star b := ab + a + b
$$

> (a) Show that $(\mathbb{R} \setminus \{-1\}, \star)$ is an Abelian group!

To solve this task, we will need the definition of an Abelian group.

---

Given a set $\mathcal{G}$ and an operation $\otimes : \mathcal{G} \times \mathcal{G} \mapsto \mathcal{G}$ defined on $\mathcal{G}$, then $G:= (\mathcal{G}, \otimes)$ is called a *group* if the following properties hold:

1. *Closure* of $\mathcal{G}$ under $\otimes$: $\forall x,y \in \mathcal{G}: x \otimes y \in \mathcal{G}$.
2. *Associativity*: $\forall x,y \in \mathcal{G}: (x\otimes y) \otimes z = x \otimes (y \otimes z)$
3. *Neutral Element*: $\exists e \in \mathcal{G} \forall x \in \mathcal{G} : x \otimes e = x$ and $e \otimes x = x$
4. *Inverse element*: $\forall x \in \mathcal{G} \exists y \in \mathcal{G} : x \otimes y = e$ and $y\otimes x = e$

For an *Abelian group* (named after Niels Henrik Abel), we additionally need:

5. *Commutativity*: $\forall x,y \in \mathcal{G}: x \otimes y = y \otimes x$

---

To show that $(\mathbb{R} \setminus \{ -1\}, \star)$ is an Abelian group, we need to show that the required properties hold.

---

1. *Closure*

Using the closure of multiplication and addition on $\mathbb{R}$, we get $\forall a,b \in \mathbb{R}: (ab + a + b) \in \mathbb{R}$.
However, we need to show that $\nexists a,b \in \mathcal{G}: ab +a +b = -1$.

We will proof that by contradiction (reductio ad absurdum): Let's assume $\exists a,b \in \mathcal{G}: a\star b = -1$. Then:

$$
\begin{aligned}
    & ab + a + b = -1 \\
    \iff& a (1+b) + b = -1 \\
    \iff& a (1+b) = -1 - b \\
    \iff& a = -\frac{(1+b)}{(1+b)} & (1+b) \neq 0 \iff b\neq-1\\
    \iff& a = -1 \notin \mathcal{G} & \bot
\end{aligned}
$$

---

2. Associativity

$$
\begin{aligned}
    \forall x,y,z \in \mathcal{G}: (x \star y) \star z &= (xy + x+y) \star z\\
    &= (xy +x +y)z + (xy+x+y) + z \\
    &= xyz +xz+yz + xy + x + y+z \\
    &= xyz + xy + yz + xz + x + z + y \\
    &= y (xz+x+z) + (xz + x + z) + y \\
    &= y \star (xz + x + z) \\
    &= y \star (x \star z) && \top
\end{aligned}
$$

---

3. Neutral Element

$$
\begin{aligned}
    & x \star e = x \\
    \iff & xe + x + e = x \\
    \iff & e(x+1) = 0 \\
    \iff & e = 0 \in \mathcal{G} && \top
\end{aligned}
$$

Similarly for $e \star x$.

---

4. Inverse Element

$$
\begin{aligned}
    & x \star y = e \\
    \iff & xy + x + y = 0 \\
    \iff & y(x+1) = -x \\
    \iff & y = -\frac{x}{x+1} && \top
\end{aligned}
$$

---

5. Commutativity

This one follows directly from the commuativity of multiplication and addition.

$$
\begin{aligned}
    \forall a,b\in \mathcal{G}: a \star b &= ab + a + b \\
    &= ba + b + a \\
    &= b \star a && \top
\end{aligned}
$$

---

Therefore, $(\mathbb{R} \setminus \{-1\}, \star)$ has all properties of an abelian group.

> (b) Solve $3 \star x \star x = 15$!

$$
\begin{aligned}
    & 3 \star x \star x = 15 \\
    \iff & (3x + 3 + x) \star x = 15 \\
    \iff & (3x+3+x)x + (3x+3+x) + x = 15 \\
    \iff & 3x^2 + 3x + x^2 + 3x + 3 +x + x = 15 \\
    \iff & 4 x^2 + 8x + 3 = 15 \\
    \iff & 4 x^2 + 8x - 12 = 0 \\
    \iff & (2x + 2)^2 - 16 = 0 \\
    \iff & 2x +2 = \pm 4 \\
    \iff & x \in \{1, -3\} && \top
\end{aligned}
$$

In [2]:
star = lambda x, y: x*y + x + y

print("3*1*1\t=", star(3, star(1, 1)))
print("3*-3*-3\t=", star(3, star(-3, -3)))

3*1*1	= 15
3*-3*-3	= 15


## 2.2 Congruence Class

Let $n$ be in $\mathbb{N} \setminus \{0\}$. Let $k, x$ be in $\mathbb{Z}$. We define the *congurence class* $\bar{k}$ of the integer $k$ as the set:

$$
\begin{aligned}
    \bar{k} &= \{ x \in \mathbb{Z} \mid x - k = 0 \pmod{n}\} \\
    &= \{ x\in \mathbb{Z} \mid (\exists a \in \mathbb{Z}): (x-k = n\cdot a)\}
\end{aligned}
$$

We now define $\mathbb{Z} / n\mathbb{Z}$ as the set of all congruence classes modulo $n$. Euclidean division implies that this set is a finite set containing $n$ elements:

$$
    \mathbb{Z}_n = \{ \bar{0}, \bar{1}, \ldots, \overline{n - 1}\}
$$

For all $\bar{a}, \bar{b} \in \mathbb{Z}_n$, we define:

$$
    \bar{a} \oplus \bar{b} := \overline{a+b}
$$

> Show that $(\mathbb{Z}_n, \oplus)$ is a group. Is it Abelian?

1. Closure

$$
\begin{aligned}
    & \forall \bar{a},\bar{b}: \bar{a} \oplus \bar{b} = \overline{a+b} \in \mathbb{Z}_n \\
    \iff & \{ x \in \mathbb{Z} \mid x - (a + b) = 0 \pmod{n}\} \in \mathbb{Z}_n \\
    \iff & \overline{(a+b) \bmod n} \in \mathbb{Z}_n & \top
\end{aligned}
$$

2. Associativity

$$
\begin{aligned}
    \forall \bar{a},\bar{b}, \bar{c} \in \mathbb{Z}_n: (\bar{a} \oplus \bar{b}) \oplus \bar{c} &= \overline{a+b} \oplus c \\
    &= \overline{(a+b)+c} \\
    &= \overline{a+(b+c)} \\
    & = \bar{a} \oplus (\bar{b} \oplus \bar{c}) & \top
\end{aligned}
$$

3. Neutral Element

$$
\begin{aligned}
    &\forall \bar{x} \in \mathbb{Z}_n \exists{e} \in \mathbb{Z}_n: \bar{x} \oplus \bar{e} = \bar{x} \\
    \iff& \overline{x+e} = \bar{x} \\
    \iff& e = 0 \\
    \iff& \bar{e} = \bar{0} & \top
\end{aligned}
$$

Similar for $\bar{e} \oplus \bar{x} = \bar{x}$.

4. Inverse Element

$$
\begin{aligned}
    &\forall \bar{x} \in \mathbb{Z}_n \exists y \in \mathbb{Z}: \bar{x} \oplus \bar{y} = \bar{e} \\
    \iff& \overline{x+y} = \bar{0} \\
    \iff& \overline{x+y} = \bar{0} \\
    \iff& y = -x \pmod{n} \\
    \iff& \bar{y} = \overline{-x\bmod{n}} \in \mathbb{Z}_n & \top
\end{aligned}
$$


5. Commutativity

$$
\begin{aligned}
    \forall \bar{a},\bar{b}: \bar{a} \oplus \bar{b} &= \overline{a+b} \\
    &= \overline{b+a} \\
    &= \bar{b} \oplus \bar{a} & \top
\end{aligned}
$$

Yes, $(\mathbb{Z}_n, \oplus)$ is an Abelian group.

> (b) Let $\bar{a} \otimes \bar{b} = \overline{a \times b}$. Draw the times table for $\mathbb{Z}_5 \setminus \{\bar{0}\}$ under $\otimes$.

In [3]:
from IPython.display import Markdown

def display_times_table(n):
    table = "| a\\b |" + "|".join(f"{b}" for b in range(1,n)) + "|\n"
    table += "|" + "|".join(["---"] * n) + "|\n"

    for a in range(1,n):
        table += f"| {a} |"
        for b in range(1,n):
            x = (a*b) % n
            table += f"{x} |"
        table += "\n"
    return table

Markdown(display_times_table(5))

| a\b |1|2|3|4|
|---|---|---|---|---|
| 1 |1 |2 |3 |4 |
| 2 |2 |4 |1 |3 |
| 3 |3 |1 |4 |2 |
| 4 |4 |3 |2 |1 |


In [4]:
Markdown(display_times_table(8))

| a\b |1|2|3|4|5|6|7|
|---|---|---|---|---|---|---|---|
| 1 |1 |2 |3 |4 |5 |6 |7 |
| 2 |2 |4 |6 |0 |2 |4 |6 |
| 3 |3 |6 |1 |4 |7 |2 |5 |
| 4 |4 |0 |4 |0 |4 |0 |4 |
| 5 |5 |2 |7 |4 |1 |6 |3 |
| 6 |6 |4 |2 |0 |6 |4 |2 |
| 7 |7 |6 |5 |4 |3 |2 |1 |


From the times table, we can see that $\bar{4} \otimes \bar{2} = \bar{2} \otimes \bar{4} = \bar{0} \notin \mathbb{Z}_8$. Therefore, $\mathbb{Z}_8$ is not closed under $\otimes$, and not a group. $\top$

> (d) Bezeout theorem states that two integers $a$ and $b$ are relatively prime (i.e., $\mathrm{gcd}(a,b)=1$), if and only if there exist two integers $u$ and $v$ such that $au +bv = 1$. Show that $(\mathbb{Z}_n \setminus \bar{0}, \otimes)$ is a group if and only if $n \in \mathbb{N} \setminus \set{0}$ is prime.

Since we have an *if and only if* ($\iff$), we need to show both directions:

1. $(\mathbb{Z}_n \setminus \bar{0}, \otimes)$ is a group $\implies$ $n$ is prime

If $(\mathbb{Z}_n \setminus \bar{0}, \otimes)$ is a group, for each element, there exists an inverse element:

$$
    \begin{align}
        &\forall \bar{x} \in \mathbb{Z}_n \setminus \bar{0}: \exists \bar{u}: \bar{x} \otimes \bar{u} = \bar{1} \\
        \iff & \forall \bar{x} \in \mathbb{Z}_n \setminus \bar{0}: \exists \bar{u} \in \mathbb{Z}_n \setminus \set{0}:
            x \cdot u - 1 = 0 \pmod{n} \\
        \iff & \forall \bar{x} \in \mathbb{Z}_n \setminus \bar{0}: \exists \bar{u} \in \mathbb{Z}_n \setminus \set{0}: \exists{v} \in \mathbb{Z}:
            x \cdot u + n \cdot v = 1 && (\text{apply Bezout's theorem})\\\
        \iff & \forall \bar{x} \in \mathbb{Z}_n \setminus \bar{0}:
            \mathrm{gcd}(x, n) = 1 \\
        \iff & \mathrm{prime}(n)\\ 
    \end{align}

$$



2. $(\mathbb{Z}_n \setminus \bar{0}, \otimes)$ is a group $\impliedby$ $n$ is prime

Even if $n$ is not prime, we $(\mathbb{Z}_n\setminus \bar{0}, \otimes)$ is associative and has a neutral element $\bar{1}$.
However, we need to show that it is only closed and has an inverse element, if $n$ is prime.

Let $\bar{x},\bar{y} \in \mathbb{Z}_n$ so that $\bar{x} \otimes \bar{y} = \bar{0} \iff xy = 0 \pmod{n}$. Since $n$ is prime, either $x = 0 \pmod{n}$ or $y = 0 \pmod{n}$.
Then:

$$
    \exists a \in \mathbb{N}: x \cdot y = a \cdot n
    \iff x = \frac{a}{y} \cdot n
$$

But since $x < n$ and n is prime i.e., cannot be factorized further, this is a contradiction. Therefore, if $n$ is prime, $\mathbb{Z_n} \setminus \bar{0}$ is closed.

If $n$ is prime, then $\forall x \in [0, n-1]: \mathrm{gcd}(x, n) = 1$ by definition. If we apply *Bezeouts theorem*:

$$
    \begin{align}
    &\forall x \in [1, n-1]: \exists u,v \in \mathbb{Z}: x \cdot u + n \cdot v = 1 \\
    \iff& \forall x \in [1, n-1] : \exists u \in \mathbb{Z}: x \cdot u = 1 \pmod n\\
    \iff& \forall \bar{x} \in \mathbb{Z}_n \setminus \set{0}: \exists u \in \mathbb{Z}_n \setminus \set{0}: \bar{x} \otimes \bar{u} = \bar{1}
    \end{align}
$$

Therefore, if $n$ is prime, each element in $\mathbb{Z}_n \setminus \set{0}$ has an inverse element.

Thus, $(\mathbb{Z}_n \setminus \bar{0}, \otimes)$ is a group $\impliedby$ $n$ is prime. $\top$

## 2.3 Matrix Group

> Consider set $\mathcal{G}$ of $3\times 3$ matrices defined as follows:
>
>    $$
>        \mathcal{G} = \left\{
>            \begin{bmatrix}
>                1 & x & z \\
>                0 & 1 & y \\
>                0 & 0 & 1 \\
>            \end{bmatrix} \in \mathbb{R}^{3 \times 3} \mid x,y,z \in \mathbb{R}
>        \right\}
>    $$
> We define $\cdot$ as standard matrix multiplication. Is $(\mathcal{G}, \cdot)$ a group?
> If yes, is it Abelian?

Let's consider the result of the group operation $\cdot$ for any $a,b \in \mathcal{G}$:

$$
    \forall A, B \in \mathcal{G}:
    A \cdot B = 
    \begin{bmatrix}
        1 & x_1 & z_1 \\
        0 & 1 & y_1 \\
        0 & 0 & 1 \\
    \end{bmatrix}
    \cdot
    \begin{bmatrix}
        1 & x_2 & z_2 \\
        0 & 1 & y_2 \\
        0 & 0 & 1 \\
    \end{bmatrix}
    =
    \begin{bmatrix}
        1 & x_2 + x_1 & z_2 + x_1 y_2 + z_1 \\
        0 & 1   & y_2 + y_1 \\
        0 & 0   & 1 \\
    \end{bmatrix}
$$

---

1. Closed

$$
\forall x_1, x_2, y_1, y_2, z_1, z_2 \in \mathbb{R}: \exists x_3, y_3, z_3 \in \mathbb{R}:
    \begin{bmatrix}
        1 & x_2 + x_1 & z_2 + x_1 y_2 + z_1 \\
        0 & 1   & y_2 + y_1 \\
        0 & 0   & 1 \\
    \end{bmatrix}
    =
    \begin{bmatrix}
        1 & x_3 & z_3 \\
        0 & 1   & y_3 \\
        0 & 0   & 1 \\
    \end{bmatrix} 
$$

Therefore, $\forall A, B \in \mathcal{G}: A \cdot B \in \mathcal{G}$. $\top$

---

2. Associativity

---

3. Neutral Element

Since the identity matrix $I\in \mathcal{G}$, we have a neutral element:

$$
    \forall A \in \mathcal{G}\exists I \in \mathcal{G}:
    A \cdot I = 
    \begin{bmatrix}
        1 & x_1 & z_1 \\
        0 & 1 & y_1 \\
        0 & 0 & 1 \\
    \end{bmatrix}
    \cdot
    \begin{bmatrix}
        1 & 0 & 0 \\
        0 & 1 & 0 \\
        0 & 0 & 1 \\
    \end{bmatrix}
    =
    \begin{bmatrix}
        1 & x_1 & z_1 \\
        0 & 1 & y_1 \\
        0 & 0 & 1 \\
    \end{bmatrix}
$$

---

4. Inverse Element

$$
    \forall A \in \mathcal{G}\exists A^{-1} \in \mathcal{G}:
    A \cdot A^{-1} = 
    \begin{bmatrix}
        1 & x_1 & z_1 \\
        0 & 1 & y_1 \\
        0 & 0 & 1 \\
    \end{bmatrix}
    \cdot
    \begin{bmatrix}
        1 & -x_1 & x_1 y_1 - z_1\\
        0 & 1 & -y_1 \\
        0 & 0 & 1 \\
    \end{bmatrix}
    =
    \begin{bmatrix}
        1 & 0 & 0 \\
        0 & 1   & 0 \\
        0 & 0   & 1 \\
    \end{bmatrix}
$$

---

Therefore, we can conclude that $(\mathcal{G}, \cdot)$ is a group. $\top$

---
5. Commutativity
---
$$
    \begin{bmatrix}
        1 & x_1 & z_1 \\
        0 & 1 & y_1 \\
        0 & 0 & 1 \\
    \end{bmatrix}
    \cdot
    \begin{bmatrix}
        1 & x_2 & z_2 \\
        0 & 1 & y_2 \\
        0 & 0 & 1 \\
    \end{bmatrix}
    =
    \begin{bmatrix}
        1 & x_2 + x_1 & z_2 + x_1 y_2 + z_1 \\
        0 & 1   & y_2 + y_1 \\
        0 & 0   & 1 \\
    \end{bmatrix}
$$

$$
    \begin{bmatrix}
        1 & x_2 & z_2 \\
        0 & 1 & y_2 \\
        0 & 0 & 1 \\
    \end{bmatrix}
    \cdot
    \begin{bmatrix}
        1 & x_1 & z_1 \\
        0 & 1 & y_1 \\
        0 & 0 & 1 \\
    \end{bmatrix}
    =
    \begin{bmatrix}
        1 & x_1 + x_2 & z_1 + x_2 y_1 + z_2 \\
        0 & 1   & y_1 + y_2 \\
        0 & 0   & 1 \\
    \end{bmatrix}
$$

Since $\exists x_1, x_2, y_1, y_2, z_1, z_2 \in \mathbb{R}: z_2 + x_1 y_2 + z_1 \neq z_1 + x_2 y_1 + z_2$, $(\mathcal{G}, \cdot)$ is not an Abelian group. $\top$

In [5]:
import numpy as np

def xyz_matrix(x,y,z):
    return np.array([[1, x, z], [0, 1, y], [0,0,1]])


M1 = xyz_matrix(1,2,3)
M2 = xyz_matrix(4,5,6)

print(M1 @ M2)
print("---")
print(M2 @ M1)
print("---")
print(np.all(M1 @ M2 == M2 @ M1))

[[ 1  5 14]
 [ 0  1  7]
 [ 0  0  1]]
---
[[ 1  5 17]
 [ 0  1  7]
 [ 0  0  1]]
---
False


In [6]:
def xyz_inverse(x,y,z):
    return np.array([[1, -x, x * y - z], [0,1,-y], [0,0,1]])

print(xyz_matrix(1,2,3) @ xyz_inverse(1,2,3))
print("---")
print(xyz_matrix(4,5,6) @ xyz_inverse(4,5,6))

[[1 0 0]
 [0 1 0]
 [0 0 1]]
---
[[1 0 0]
 [0 1 0]
 [0 0 1]]


## 2.4 Matirx Products


> Compute the following matrix products, if possible:

> (a)
> $$
>   \begin{bmatrix}
>       1   &   2   \\
>       4   &   5   \\
>       7   &   8   \\
>   \end{bmatrix} 
>   \begin{bmatrix}
>       1 & 1 & 0 \\
>       0 & 0 & 1 \\
>       1 & 0 & 1 \\
>   \end{bmatrix}
> $$

This is not a valid matrix product, since $[A] = [3,2]$ and $[B] = [3,3]$, and $2 \neq 3$.

In [12]:
try:
    np.array([[1,2], [4,5], [7,8]]) @ np.array([[1,1,0],[0,1,1], [1,0,1]])
except ValueError as e:
    print(e)

matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)


> (b)
> $$
>   \begin{bmatrix}
>       1 & 2 & 3 \\
>       4 & 5 & 6 \\
>       7 & 8 & 9 \\
>   \end{bmatrix} 
>   \begin{bmatrix}
>       1 & 1 & 0 \\
>       0 & 0 & 1 \\
>       1 & 0 & 1 \\
>   \end{bmatrix}
> $$

$$
    \begin{bmatrix}
        4 & 3 & 5 \\
        10 & 9 & 11 \\
        16 & 15 & 17 \\
    \end{bmatrix}
$$

In [9]:
np.array([[1,2,3], [4,5,6], [7,8,9]]) @ np.array([[1,1,0],[0,1,1], [1,0,1]])

array([[ 4,  3,  5],
       [10,  9, 11],
       [16, 15, 17]])

> (c)
> $$
>  \begin{bmatrix}
>       1 & 1 & 0 \\
>       0 & 0 & 1 \\
>       1 & 0 & 1 \\
>   \end{bmatrix}
>   \begin{bmatrix}
>       1 & 2 & 3 \\
>       4 & 5 & 6 \\
>       7 & 8 & 9 \\
>   \end{bmatrix} 
> $$

$$
    \begin{bmatrix}
        5 & 7 & 9 \\
        11 & 13 & 15 \\
        8 & 10 & 12 \\
    \end{bmatrix}
$$

In [10]:
np.array([[1,1,0],[0,1,1], [1,0,1]]) @ np.array([[1,2,3], [4,5,6], [7,8,9]])

array([[ 5,  7,  9],
       [11, 13, 15],
       [ 8, 10, 12]])

> (d)
> $$
>  \begin{bmatrix}
>       1 & 2 & 1 & 2 \\
>       4 & 1 & -1 & -4 \\
>   \end{bmatrix}
>   \begin{bmatrix}
>       0 & 3 \\
>       1 & -1 \\
>       2 & 1 \\
>       5 & 2 \\
>   \end{bmatrix} 
> $$

$$
    \begin{bmatrix}
        14 & 6 \\
        -21 & 2 \\
    \end{bmatrix}
$$

In [13]:
np.array([[1, 2, 1, 2], [4, 1, -1, -4]]) @ np.array([[0, 3], [1, -1], [2, 1], [5, 2]])

array([[ 14,   6],
       [-21,   2]])

> (e)
> $$
>   \begin{bmatrix}
>       0 & 3 \\
>       1 & -1 \\
>       2 & 1 \\
>       5 & 2 \\
>   \end{bmatrix} 
>   \begin{bmatrix}
>       1 & 2 & 1 & 2 \\
>       4 & 1 & -1 & -4 \\
>   \end{bmatrix}
> $$

$$
    \begin{bmatrix}
        12 & 3 & -3 & -12 \\
        -3 & 1 & 2  & 6 \\
        6  & 5 & 1  & 0 \\
        13 & 12 & 3 & 2 \\
    \end{bmatrix}
$$

In [15]:
np.array([[0,3], [1, -1], [2, 1], [5, 2]]) @ np.array([[1, 2, 1, 2], [4, 1, -1, -4]])

array([[ 12,   3,  -3, -12],
       [ -3,   1,   2,   6],
       [  6,   5,   1,   0],
       [ 13,  12,   3,   2]])