## 2.19 Endomorphism

> Consider an endomorphism $\Phi: \mathbb{R}^3 \rightarrow \mathbb{R}^3$, whose transformation matrix (with rspect to the standard basis in $\mathbb{R}^3$) is: 
> $$
    A_\Phi = \begin{bmatrix}
        1 & 1 & 0\\
        1 & -1 & 0 \\
        1 & 1 & 1\\
        \end{bmatrix}$$

> (a) Determine $\mathrm{ker}(\Phi)$ and $\mathrm{Im}(\Phi)$?

Since $\Phi$ is an endomorphism, it is linear and maps $\mathbb{R}^3$ onto itself.

$$
    \begin{bmatrix}
        1 & 1 & 0\\
        1 & -1 & 0 \\
        1 & 1 & 1\\
    \end{bmatrix}
    \leadsto
    \begin{bmatrix}
        1 & 0 & 0\\
        0 & 1 & 0 \\
        0 & 0 & 1\\
    \end{bmatrix}
$$

Therefore, the kernel is:

$$
    \mathrm{ker}(\Phi) = \{ \boldsymbol{0} \}
$$

The image $\mathrm{Im}(\Phi)$ is given by the column space:

$$
    \mathrm{Im}(\Phi) = 
    \mathrm{span}[
        \begin{bmatrix} 1 \\ 1 \\ 1 \end{bmatrix},
        \begin{bmatrix} 1 \\ -1 \\ 1 \end{bmatrix},
        \begin{bmatrix} 0 \\ 0 \\ 1 \end{bmatrix}
    ]
    = \mathbb{R}^{3}
$$


> (b) Determine the transformation matrix $\tilde{A}_\Phi$ with respect to the basis:
> $$
    B = (
        \begin{bmatrix} 1 \\ 1 \\ 1 \end{bmatrix},
        \begin{bmatrix} 1 \\ 2 \\ 1 \end{bmatrix},
        \begin{bmatrix} 1 \\ 0 \\ 0 \end{bmatrix}
    ),$$
> i.e., perform a basis change toward the new basis $B$.

The new transformation matrix $\tilde{A}_\Phi$ is given by:

$$
    \tilde{A}_\Phi = T^{-1} A_\Phi S
$$

Since domain and codomain of $\Phi$ are both $\mathbb{R}^3$, $T$ and $S$ are both matrices that map coordinates with regard to the new basis $B$ onto the standard basis of $\mathbb{R}^3$.

Essentially, this new transformation matrix maps the coordinates with regard to $B$ back to the original coordinates, applies the old transformation matrix, and maps them back via $T^{-1}$.

Since the original basis is the standard basis, finding $S$ and $T$ for the new basis $B$ is trivial:

$$
    S = T = \begin{bmatrix}
        1 & 1 & 1 \\
        1 & 2 & 0 \\
        1 & 1 & 0 \\
    \end{bmatrix}
$$

Now, we need to find the inverse $T^{-1}$, given by:

$$
    \left[\begin{array}{ccc|ccc}
        1 & 1 & 1 & 1 & 0 & 0 \\
        1 & 2 & 0 & 0 & 1 & 0 \\
        1 & 1 & 0 & 0 & 0 & 1 \\
    \end{array}\right]
    \leadsto
    \left[\begin{array}{ccc|ccc}
        1 & 0 & 0 & 0 & -1 & 2 \\
        0 & 1 & 0 & 0 & 1 & -1 \\
        0 & 0 & 1 & 1 & 0 & -1 \\
    \end{array}\right]
$$

This gives us:

$$
    \tilde{A}_\Phi =
    \begin{bmatrix}
        6 & 9 & 1 \\
        -3 & -5 & 0 \\
        -1 & -1 & 0
    \end{bmatrix}
$$

In [2]:
import numpy as np

T = np.array([
    [1, 1, 1],
    [1, 2, 0],
    [1, 1, 0]
])

S = T.copy()

T_inv = np.linalg.inv(T)

print(T_inv)

[[ 0. -1.  2.]
 [ 0.  1. -1.]
 [ 1. -0. -1.]]


In [3]:
A = np.array([
    [1, 1, 0],
    [1, -1, 0],
    [1, 1, 1]
])

In [4]:
T_inv @ A @ S

array([[ 6.,  9.,  1.],
       [-3., -5.,  0.],
       [-1., -1.,  0.]])

In [5]:
T_inv @ A

array([[ 1.,  3.,  2.],
       [ 0., -2., -1.],
       [ 0.,  0., -1.]])