## Subspace Intersection

> This task seemed pretty tedious, so I am not sure if the solution is correct.
> Another approach to find the intersection of the subspace is given by the [Zassenhaus algorithm](https://en.wikipedia.org/wiki/Zassenhaus_algorithm).

> Consider two subspaces
> $$
    \begin{align}
    U_1 &= span\left[
        \begin{bmatrix}
            1\\
            1\\
            -3\\
            1
        \end{bmatrix},
        \begin{bmatrix}
            2\\
            -1\\
            0\\
            -1
        \end{bmatrix},
        \begin{bmatrix}
            -1\\
            1\\
            -1\\
            1
        \end{bmatrix}
    \right]\\
    U_2 &= span\left[
        \begin{bmatrix}
            -1\\
            -2\\
            2\\
            1
        \end{bmatrix},
        \begin{bmatrix}
            2\\
            -2\\
            0\\
            0
        \end{bmatrix},
        \begin{bmatrix}
            -3\\
            6\\
            -2\\
            -1
        \end{bmatrix}
    \right]
    \end{align}$$
> Determine a basis of $U_1 \cap U_2$.

First, we will find a basis for each of the subspaces by checking linear independence. This is not necessarily required, but makes it easier to compute the basis of the intersection:

$$
\begin{align}
    \begin{bmatrix}
        1 & 2 & -1\\
        1 & -1 & 1\\
        -3 & 0 & -1\\
        1 & -1 & 1\
    \end{bmatrix}
    &\leadsto
    \begin{bmatrix}
        1 & -1 & 1\\
        0 & 3 & -2\\
        0 & 0 & 0\\
        0 & 0 & 0 \\
    \end{bmatrix}
    &
    U_1 &= span\left[
        \begin{bmatrix}
            1\\
            1\\
            -3\\
            1
        \end{bmatrix},
        \begin{bmatrix}
            2\\
            -1\\
            0\\
            -1
        \end{bmatrix}
    \right]\\
    \end{align}
$$



$$
    \begin{align}
    \begin{bmatrix}
        -1 & 2 & -3\\
        -2 & -2 & 6\\
        2 & 0 & -2\\
        1 & 0 & -1\\
    \end{bmatrix}
    &\leadsto
    \begin{bmatrix}
        1 & 0 & -1\\
        0 & 2 & -4\\
        0 & 0 & 0\\
        0 & 0 & 0\\
    \end{bmatrix}
    &
    U_2 &= span\left[
        \begin{bmatrix}
            -1\\
            -2\\
            2\\
            1
        \end{bmatrix},
        \begin{bmatrix}
            2\\
            -2\\
            0\\
            0
        \end{bmatrix}
    \right]
    \end{align}
$$

Now, we just need to consider the bases of the subspaces to find a basis of the subspace intersection.
If a vector is in the intersection, then, it must also be both in $U_1$ and $U_2$.
This means, forall $x \in U_1 \cap U_2$, there are $\alpha$ and $\beta$, so that $x = [U_1] \alpha = [U_2] \beta$.
Therefore, all solutions to $[U_1 | U_2] [\alpha \beta]^T = 0$ are basis vectors of the intersection:

$$
    \begin{bmatrix}
        1 & 2 & -1 & 2\\
        1 & -1 & -2 & -2\\
        -3 & 0 & 2 & 0\\
        1 & -1 & 1 & 0\\
    \end{bmatrix}
    \leadsto
    \begin{bmatrix}
        1 & 0 & 0 & 4/9\\
        0 & 1 & 0 & 10/9\\
        0 & 0 & 1 & 2/3\\
        0 & 0 & 0 & 0\\
    \end{bmatrix}
$$

With the  minus-1-Trick:

$$
    S = \left\{ \lambda_1
        \begin{bmatrix}
            4 / 9\\
            10 / 9\\
            2/ 3\\
            -1\\
        \end{bmatrix}
    \right\}
$$

Now, we can use any value of $\lambda_1$ to find the basis vector. For $\lambda_1 = 9$:

$$
    4 * \begin{bmatrix}1 \\ 1 \\ -3 \\ 1\end{bmatrix} + 10 * \begin{bmatrix} 2 \\ -1 \\ 0 \\ -1\end{bmatrix} =
    \begin{bmatrix} 24 \\ -6 \\ -12 \\ -6 \end{bmatrix}
$$

$$
    U_1 \cap U_2 = \mathrm{span}\left[ \begin{bmatrix} 24 \\ -6 \\ -12 \\ -6 \end{bmatrix} \right]
$$

In [1]:
import numpy as np

U1 = np.array([[1, 2, -1], [1, -1, 1], [-3, 0, -1], [1, -1, 1]])
U2 = np.array([[-1, 2, -3], [-2, -2, 6], [2, 0, -2], [1, 0, -1]])

u = np.array([[24], [-6], [-12], [-6]])

In [2]:
from math4ml import rref, array_to_math

rref(np.concat([U1, u], axis=1))

array([[ 1,  0,  0,  4],
       [ 0,  1,  0, 10],
       [ 0,  0,  1,  0],
       [ 0,  0,  0,  0]])

In [ ]:
np.linalg.solve(U1[:2, :2], u[:2])

array([[ 4.],
       [10.]])

In [12]:
np.linalg.solve(U2[:2, :2], u[:2])

array([[-6.],
       [ 9.]])